### ISSUE TITLE
Test Certificate based Authentication

### ISSUE THREAD

**Issue by switschel** [SoftwareAG/cumulocity-devicemanagement-agent#15]

**Comment by z8674558** [comment]
hi. do you have a plan to add e2e test to this repository? If yes I would like to work on it, though I am not sure if c8y provides something like a sandbox tenant to test the agent in github actions

**Comment by switschel** [comment]
Not yet planned as the main goal was not to run this productive more likely to demonstrate some features within Cumulocity.
Does not mean that you can't work on it ;-) If needed I can create a test tenant. Just let me know.

**Comment by z8674558** [comment]
sure, thanks!
