### ISSUE TITLE
Create Dockerfile to mass scale Agent

### ISSUE THREAD

**Issue by switschel** [SoftwareAG/cumulocity-devicemanagement-agent#16]

**Comment by mbay-SAG** [comment]
You could basically do this by providing an docker-compose file 

version: "3.0"
services:
   agent:
    build: .

and the following mass_start.sh script:

docker-compose up --build -d --scale agent=$1
echo "You can copy everything below this line and save as CSV file to use bulk registration!"
echo "ID;PATH"
docker stats --no-stream --format "{{.Container}};"

by calling . mass_start.sh $NUMBEROFCONTAINERS it will scale agents and print the ID to the prompt which directly could be used for bulk registration within c8y as csv.

**Comment by mbay-SAG** [comment]
Added the script and the docker-compose file, feel free to comment and merge.
