### ISSUE TITLE
Integrate key generation in docker file 

### ISSUE THREAD

**Issue by switschel** [SoftwareAG/cumulocity-devicemanagement-agent#25]

**Comment by z8674558** [comment]
this task means generating certs in dockerfile and using them at authentication? Can I work on this?

**Comment by switschel** [comment]
Yep, generation & test of certificates was still open. Would be very happy if you could contribute this!

**Comment by switschel** [comment]
@z8674558: I just checked. Can you also provide an updated agent.ini where the certs are configured correctly? Also the certs should use the docker container ID as device ID not "pyagent0001".

**Comment by z8674558** [comment]
true. will submit PR
