### ISSUE TITLE
Review Log Module

### ISSUE THREAD

**Issue by elielias** [SoftwareAG/cumulocity-devicemanagement-agent#29]
The LogHandler Module needs to be reviewed

**Comment by switschel** [comment]
I would suggest to use logger instead of "print"
E.g. line 68 in logfile_handler.py
`print('\n` deviceid: {}\n starttime: {}\n endtime: {}\n searchtext:{}\n maximumlines:{} \n'.format(deviceid, starttime, endtime, searchtext, maximumlines))`

**Comment by switschel** [comment]
Add Exception Handling try - except in handleOperation
In case of error set the Operation to failed.

**Comment by elielias** [comment]
> Line 131:
> binaryurl = self.agent.rest_client.upload_binary_logfile(internal_id, payload, file)
> function upload_binary_logfile does not exist in main branch.

function is pushed now
