### ISSUE TITLE
Dockerfile fails for arm (e.g. Mac M1)

### ISSUE THREAD

**Issue by mbay-SAG** [SoftwareAG/cumulocity-devicemanagement-agent#40]
In the Dockerfile the arch is set [hardcoded](https://github.com/SoftwareAG/cumulocity-devicemanagement-agent/blob/0df64cf285216cbb5cb8d0cfc262616b15427c4a/docker/Dockerfile#L43).

Thus the building fails on arm. arch should be handed via environment of host system.

**Comment by switschel** [comment]
Fixed with 2316821582455532ca904916a637bba13be80cbe

**Comment by switschel** [comment]
Fixed with 1d97d34
