### ISSUE TITLE
Add hint to set appropriate End of Line Sequence

### ISSUE THREAD

**Issue by mbie-sag** [SoftwareAG/cumulocity-devicemanagement-agent#41]
When I try to run the agent on a Windows machine, I recognized VSCODE did not use the right EOL Sequence for running the *.sh scripts. So maybe put one hint in the documentation to set "LF" or "\n" for End of Line Sequence in Windows environments. "Auto" detection did not work for me (at least not in VSCODE).

**Comment by switschel** [comment]
For running in Windows you can use the [start.bat](https://github.com/SoftwareAG/cumulocity-devicemanagement-agent/blob/main/start.bat)

**Comment by switschel** [comment]
Discussed with Marco. For some reason all files were touched with a wrong EOL. Reverting fixed it.
