### ISSUE TITLE
Build and run instructions issues

### ISSUE THREAD

**Issue by mstoffel-sag** [SoftwareAG/cumulocity-devicemanagement-agent#44]
I would like to run the agent in wsl2 Ubuntu.
When I follow the description in the build step:

* Build
pip install -r requirements.txt
pip install .

apt install python-apt -> this cannot be run without sudo

* Run
sudo c8ydm.start -> will not be found since the agent was installed without sudo

When I do all the steps using sudo or not and execute c8ydm.start I always get:

  from c8ydm.core.apt_package_manager import AptPackageManager
  File "/home/mstoffel/.local/lib/python3.8/site-packages/c8ydm/core/apt_package_manager.py", line 23, in <module>
    if 'Linux' == platform.system() and ('debian' == platform.linux_distribution()[0] or 'ubuntu' == platform.linux_distribution()[0]):
AttributeError: module 'platform' has no attribute 'linux_distribution'

**Comment by switschel** [comment]
I aligned the README accordingly. The issue should be fixed for Pythons > 3.7 now. Can you do a test?
